### ISSUE TITLE
E2E fails with local run 

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#323]
**Describe the bug**

**To Reproduce**
1. Checkout project from 'dev'
2. yarn reset
3. yarn run cy:ci
4. See failing tests 

**Expected behavior**
No failed tests, all pass

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS

**Additional context**

```sh
  Running:  login.spec.mjs                                                                  (1 of 2)


  Logging In
    ✓ fail login on invalid email (2637ms)
    ✓ fail login with empty password (975ms)
    1) redirects to /home on success
    2) stay logged on browser refresh
    3) navigate to last location on browser refresh


  2 passing (19s)
  3 failing

  1) Logging In
       redirects to /home on success:
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8086/login#/login' to include '/home'
      at Context.eval (http://localhost:8086/__cypress/tests?p=e2e/cypress/integration/login.spec.mjs:124:14)

  2) Logging In
       stay logged on browser refresh:
     AssertionError: Timed out retrying after 4000ms: expected 'http://localhost:8086/login#/login' to include '/home'
      at Context.eval (http://localhost:8086/__cypress/tests?p=e2e/cypress/integration/login.spec.mjs:130:14)

  3) Logging In
       navigate to last location on browser refresh:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `[data-test-id="example"]`, but never found it.
      at Context.eval (http://localhost:8086/__cypress/tests?p=e2e/cypress/integration/login.spec.mjs:138:8)

  (Results)

```

**Comment by yzhbankov** [comment]
All works fine in my environment:
       
![image](https://user-images.githubusercontent.com/13466225/115149573-47f70480-a054-11eb-9c39-e9869ab71a4f.png)

**Comment by nesterone** [comment]
strange still an issue with local env ... need to investigate, in a perspective better to run thouse test inside docker ....
