### ISSUE TITLE
Eslint plugin import/export issue

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#50]
**Steps to reproduce:**

1. Go to project root
1. run `yarn code`

**Expected:** No error in output

**Actual:** Eslint error in output

```
ops! Something went wrong! :(

ESLint: 7.14.0

EslintPluginImportResolveError: unable to load resolver "alias".
Occurred while linting /projects/zorko-io/zorko-platform/apps/web-portal-client/lib/app/App.jsx:5
    at requireResolver (/projects/zorko-io/zorko-platform/node_modules/eslint-module-utils/resolve.js:187:17)
    at fullResolve (/projects/zorko-io/zorko-platform/node_modules/eslint-module-utils/resolve.js:138:22)
    at Function.relative (/projects/zorko-io/zorko-platform/node_modules/eslint-module-utils/resolve.js:84:10)
    at remotePath (/projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:702:351)
    at captureDependency (/projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:704:81)
    at /projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:707:42
    at Array.forEach (<anonymous>)
    at Function.ExportMap.parse (/projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:706:248)
    at Function.ExportMap.for (/projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:699:201)
    at /projects/zorko-io/zorko-platform/apps/web-portal-client/node_modules/eslint-plugin-import/lib/ExportMap.js:721:161
error Command failed with exit code 2.

lerna ERR! yarn run lint exited 2 in '@zorko-io/web-portal-client'
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nesterone** [comment]
just found in a `dev`, probably it's because `util-validation` is not declared in 'dependencies' for package.json
